name: Daily Stock Monitor

on:
  schedule:
    - cron: '0 23 * * 1-5'  # Runs at 11 PM UTC (5 PM MDT) on weekdays
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run stock monitor
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      run: |
        echo "import os" >> stock_monitor.py
        echo "newsapi = NewsApiClient(api_key=os.getenv('NEWSAPI_KEY'))" >> stock_monitor.py
        echo "openai.api_key = os.getenv('OPENAI_KEY')" >> stock_monitor.py
        python stock_monitor.py
